# Developer's Note: This is a sample _config.yml file offered with
# jekyll-theme-prologue for your convenience. To use it, move it to your
# project's root directory. Please note that the following lines are
# NECESSARY for Prologue to work correctly:
#
# theme: jekyll-theme-prologue
# collections: [sections]
#
# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.
#
# Also, be sure to customize url and baseurl for your site.
#
# ---------------------------------------------------------------
#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jiyu-Xie
subtitle: Guilin â†’ Shenzhen, China
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Jiyu-Xie
email: 11510224@mail.sustc.edu.cn
avatar: assets/images/fulls/avatar_JiyuXie_pic.jpg

# You'll want to customize url and baseurl for your own site:
#baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g./jiyu-xie.github.io/my-blog

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe

# twitter_url: https://mobile.twitter.com/308610721Ploso
# facebook_url: https://www.facebook.com/xiejiyu
# googleplus_url:
# instagram_url: https://www.instagram.com/ploso_X/
linkedin_url: https://www.linkedin.com/in/%E6%B5%8E%E5%AE%87-%E8%B0%A2-ba7675118/
github_url: https://github.com/Jiyu-Xie
# pinterest_url: https://www.pinterest.ca/JonnyJiyuXie/
# slack_url:
# dribbble_url: https://dribbble.com/Jiyu-Xie

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: 
remote_theme: jekyll-theme-prologue
collections: [sections]
